routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

// FormaPagamento
Route::get('formapagamento/{id}/enable', 'FormaPagamentoController@ativar')->name('formapagamento.enable');
Route::get('formapagamento/{id}/disable', 'FormaPagamentoController@desativar')->name('formapagamento.disable');
Route::resource('formapagamento', 'FormaPagamentoController', ['except' => [
    'destroy'
]]);

// TipoConta
Route::get('tipoconta/{id}/enable', 'TipoContaController@ativar')->name('tipoconta.enable');
Route::get('tipoconta/{id}/disable', 'TipoContaController@desativar')->name('tipoconta.disable');
Route::resource('tipoconta', 'TipoContaController', ['except' => [
    'destroy'
]]);

// Conta
Route::resource('conta', 'ContaController', ['except' => [
    'destroy'
]]);

// Pessoa
Route::view('pessoa/juridica', 'pessoa.juridica')->name('pessoa.juridica');
Route::view('pessoa/fisica', 'pessoa.fisica')->name('pessoa.fisica');
Route::view('pessoa/tecnico', 'pessoa.tecnico')->name('pessoa.tecnico');
Route::get('pessoa/{id}/upgrade', 'PessoaController@upgrade')->name('pessoa.upgrade');
Route::resource('pessoa', 'PessoaController', ['except' => [
    'destroy'
]]);

// Filiacao
Route::get('pagamentos', 'FiliacaoController@index')->name('filiacao.index');
Route::post('pagamentos/import', 'FiliacaoController@import')->name('filiacao.import');

app/FormaPagamento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Forma de pagamento de Conta
 */
class FormaPagamento extends Model
{
    protected $table = 'forma_pagamento';

    protected $fillable = [
        // string(150)
        'descricao', 
        // boolean
        'ativo'
    ];

}

app/Http/Controllers/FormaPagamentoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\FormaPagamento;

class FormaPagamentoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $formaPagamentos = FormaPagamento::all();
        return view('formapagamento.index', ['formaPagamentos' => $formaPagamentos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('formapagamento.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $formaPagamento = FormaPagamento::create( $request->except('_token') );

        return redirect()->route( 'formapagamento.show', ['id' => $formaPagamento->id ] );
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $formaPagamento = FormaPagamento::find($id);
        return view('formapagamento.show', ['formaPagamento' => $formaPagamento]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $formaPagamento = FormaPagamento::find($id);
        return view('formapagamento.edit', ['formaPagamento' => $formaPagamento]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $formaPagamento = FormaPagamento::find($id);

        $formaPagamento->fill( $request->except('_token') );

        $formaPagamento->save();

        return redirect()->route('formapagamento.show', ['id' => $formaPagamento->id] );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/formapagamento/create.blade.php
@extends('layouts.dashboard')

@section('title', 'Cadastrar Formma de Pagamento')

@section('header-left-controls')
	
@endsection

@section('page-header', 'Cadastrar Formma de Pagamento')

@section('content')
	<div class="col-md-12">
		<form action="{{ route('formapagamento.store') }}" method="POST" name="cadastro_conta_receber" id="cadastro_conta_receber">
			
			{{ csrf_field() }}

	    	<div class="panel panel-default">
			  <div class="panel-heading">Dados Pessoais</div>
			  	<div class="panel-body">
				  		
			   		<div class="form-group">
			   			<label>Código</label>
			   			<input type="text" name="codigo" class="form-control" placeholder="Código da conta. Ex: 002" required="required">
			   		</div>

			   		<div class="form-group">
			   			<label>Descrição</label>
			   			<input type="text" name="descricao" class="form-control cpf" placeholder="Descrição da conta">
			   		</div>

			  	</div>
			</div>

			

			<input type="submit" class="btn btn-success" value="Cadastrar">
		</form>
	</div>
@endsection

resources/views/formapagamento/edit.blade.php
@extends('layouts.dashboard')

@section('title', 'Editar Forma de Pagamento')

@section('header-left-controls')
	
@endsection

@section('page-header', 'Editar Forma de Pagamento')

@section('content')
	<div class="col-md-12">
		<form action="{{ route('formapagamento.update', ['id' => $formaPagamento->id ]) }}" id="editar_conta_receber" name="cadastro_conta" method="POST">
			{{ method_field('PUT') }}
			{{ csrf_field() }}
	    	
	    	<div class="panel panel-default">
			  <div class="panel-heading">Dados da conta</div>
			  	<div class="panel-body">

					<div class="form-group">
			   			<label>Código</label>
						<input type="text" name="codigo" class="form-control" placeholder="Código" value="{{ $formaPagamento->codigo }}" required="required">
					</div>

					<div class="form-group">
			   			<label>Descrição</label>
						<input type="text" name="descricao" class="form-control" placeholder="Descrição do tipo de conta" value="{{ $formaPagamento->descricao }}">
					</div>
					
			    	<div class="row">
						<div class="form-group">
							<div class="demo-checkbox">
								<input type="checkbox" id="basic_checkbox_2" value="1" class="filled-in" @if( $formaPagamento->ativo ) checked="checked" @endif>
								<label for="basic_checkbox_2">Ativo</label>
							</div>
							<input type="hidden" id="ativo" name="ativo" value="{{ $formaPagamento->ativo }}">
						</div>	
					</div>

			  	</div>
			</div>

			<input type="submit" class="btn btn-success" value="Atualizar">
		</form>
	</div>
@endsection

@section('scripts')
	<script type="text/javascript">
		$(function(){
			$('#basic_checkbox_2').change(function(){
				if ( $(this).prop('checked') ) {
					$('#ativo').val(1);	
				}else{
					$('#ativo').val(0);
				}
			});

		});
	</script>
@endsection

resources/views/formapagamento/index.blade.php
@extends('layouts.dashboard')

@section('title', 'Formas de Pagamento')

@section('header-left-controls')
	<!-- Controles da esquerda -->
@endsection

@section('page-header', 'Formas de Pagamento')

@section('header-right-controls')
	<a href="{{ route('formapagamento.create') }}" class="btn btn-primary">Novo</a>
@endsection

@section('content')
<table id="formaspagamento" class="table table-striped display">
	<thead>
		<tr>
			<th> <input type="checkbox" name="select-all-customer"> </th>
			<th>ID</th>
			<th>Código</th>
			<th>Descrição</th>
		</tr>
	</thead>
	<tbody>

		@foreach ($formaPagamentos as $formaPagamento)
			<tr>
				<td> <input type="checkbox" name="select-customer"> </td>
				<td><a href="{{ route('formapagamento.show', ['id' => $formaPagamento->id]) }}">{{ $formaPagamento->id }}</a></td>
				<td>{{ $formaPagamento->codigo }}</td>
				<td>{{ $formaPagamento->descricao }}</td>
			</tr>
		@endforeach

	</tbody>
</table>

@endsection

@section('scripts')

	<script src="{{ asset('js/datatables.min.js') }}"></script>
	<script type="text/javascript">
	  $(document).ready(function() {
	    $('#formaspagamento').DataTable({
	    	'columnDefs': [
    			{"searchable": true, "targets": 2}
	    	],
	    	'language':{
	    		"search":"Buscar registros",
	    		"emptyTable": "Não registros",
	    		"zeroRecords": "Não foram encontrados registros",
	    		"lengthMenu": "Exbir _MENU_ registros",
	    		"infoFiltered": "(filtrados de _MAX_ registros)",
	    		"info": "Exibindo _START_ a _END_ de _TOTAL_ registros",
	    		"infoEmpty": "Exibindo 0 a 0 de 0 registros",
	    		"paginate": {
	    			"first": "Primeira página",
	    			"last": "Última página",
	    			"next": "Próximo",
	    			"previous": "Anterior"
	    		}
	    	}
	    });
	  } );
	</script>

@endsection

resources/views/formapagamento/show.blade.php
@extends('layouts.dashboard')

@section('title', 'Dados da Forma de Pagamento')

@section('header-left-controls')
	<!-- Controles da esquerda -->
@endsection

@section('page-header', 'Dados da Forma de Pagamento')

@section('content')
	<div class="col-md-12">
		<div class="card">
			<div class="card-body">
				<div class="row">
					<div class="col-md-12">

						<h3 class="card-title m-b-5 pull-left"><span class="lstick"></span>Forma de Pagamento</h3>

						<div class="pull-right">
							<a href="{{ route('formapagamento.edit', ['id' => $formaPagamento->id]) }}" class="btn btn-primary"><span class="mdi mdi-account-edit"></span> Editar</a>
							<a href="#" class="btn btn-danger"><span class="mdi mdi-delete"></span>Excluir</a>	
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-body">
						<p>ID: {{ $formaPagamento->id }}</p>
						<p>Código: {{ $formaPagamento->codigo }}</p>
						<p>Descrição: {{ $formaPagamento->descricao }}</p>
						<p>Ativo: @if($formaPagamento->ativo) Sim @else Não @endif</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	
@endsection