routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

// FormaPagamento
Route::get('formapagamento/{id}/enable', 'FormaPagamentoController@ativar')->name('formapagamento.enable');
Route::get('formapagamento/{id}/disable', 'FormaPagamentoController@desativar')->name('formapagamento.disable');
Route::resource('formapagamento', 'FormaPagamentoController', ['except' => [
    'destroy'
]]);

// TipoConta
Route::get('tipoconta/{id}/enable', 'TipoContaController@ativar')->name('tipoconta.enable');
Route::get('tipoconta/{id}/disable', 'TipoContaController@desativar')->name('tipoconta.disable');
Route::resource('tipoconta', 'TipoContaController', ['except' => [
    'destroy'
]]);

// Conta
Route::resource('conta', 'ContaController', ['except' => [
    'destroy'
]]);

// Pessoa
Route::view('pessoa/juridica', 'pessoa.juridica')->name('pessoa.juridica');
Route::view('pessoa/fisica', 'pessoa.fisica')->name('pessoa.fisica');
Route::view('pessoa/tecnico', 'pessoa.tecnico')->name('pessoa.tecnico');
Route::get('pessoa/{id}/upgrade', 'PessoaController@upgrade')->name('pessoa.upgrade');
Route::resource('pessoa', 'PessoaController', ['except' => [
    'destroy'
]]);

// Filiacao
Route::get('pagamentos', 'FiliacaoController@index')->name('filiacao.index');
Route::post('pagamentos/import', 'FiliacaoController@import')->name('filiacao.import');

app/Pessoa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Entidade de pessoas físicas ou jurídicas
 */
class Pessoa extends Model
{
	const TIPO = [
		1 => 'Pessoa Jurídica',
		2 => 'Pessoa Física',
		3 => 'Técnico'
	];

    protected $table = 'pessoa';

    protected $fillable = [
		// int
		'tipo',
		// int
		'cpf_cnpj',
		// string(250)
		'nome', 
		// string(150)
		'email',
		// string(50)
		'telefone',
		// string(10)
		'cep', 
		// string(50)
		'endereco', 
		// string(150)
		'complemento', 
		// string(150)
		'bairro', 
		// string(150)
		'cidade',
		// string(10)
		'uf', 
		
		/** campos de pessoa fisica */		
		// string(20)
		'inscricao_estadual',
		// string(250)
		'razao_social',
		
		/** campos de pessoa juridica */
		// string(50)
		'rg',
		// string(10)
		'rg_uf', 
		// string(50)
		'rg_orgao'
	];

	public function matricula() {		
        return $this->hasOne('App\Matricula', 'pessoa_id');
	}

	public function tipo_descricao() {
		return self::TIPO[$this->tipo];
	}
}

app/Http/Controllers/PessoaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Pessoa;

class PessoaController extends Controller
{
    public function index()
    {
        $pessoas = Pessoa::all();
        return view('pessoa.index', ['pessoas' => $pessoas]);
    }

    public function store(Request $request)
    {
        //
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function upgrade($id)
    {
        return view('pessoa.tecnico');
    }

}

resources/views/pessoa/fisica.blade.php
@extends('layouts.dashboard')

@section('title', 'Adicionar Pessoa Física')

@section('content')
	<form action="{{ route('pessoa.store') }}" method="POST">
		<div class="col-md-12">
			<div class="card">
				<div class="card-body">
					<div>
						<h3 class="card-title m-b-5"><span class="lstick"></span>Adicionar Pessoa Física</h3>
					</div>
					{{ csrf_field() }}
					<div class="panel panel-default">
						<div class="panel-body">
							<input name="pessoa[tipo]" type="hidden" value="2" />

							<div class="row">
								<div class="form-group col-md-3">
									<label>CPF *</label>
									<input type="text" name="pessoa[cpf_cnpj]" class="form-control" required />
								</div>
								
								<div class="form-group col-md-3">
									<label>RG</label>
									<input type="text" name="pessoa[rg]" class="form-control" />
								</div>
								
								<div class="form-group col-md-3">
									<label>UF</label>
									<input type="text" name="pessoa[rg_uf]" class="form-control" />
								</div>

								<div class="form-group col-md-3">
									<label>Órgão Expedidor</label>
									<input type="text" name="pessoa[rg_orgao]" class="form-control" />
								</div>
							</div>
							
							@include('shared.pessoa')
						</div>
					</div>
				</div>
				<input type="submit" class="btn btn-success" value="Cadastrar">
			</div>
		</div>
	</form>			
@endsection

@section('scripts')
@endsection

resources/views/pessoa/index.blade.php
@extends('layouts.dashboard')

@section('title', 'Gerenciamento de Pessoas')

@section('header-left-controls')
	<!-- Controles da esquerda -->
@endsection

@section('content')

<div class="card">
	<div class="card-body">
		<h4 class="card-title">Cadastro de Pessoas</h4>
        <h6 class="card-subtitle">Gerenciamento de pessoas jurídicas, físicas e técnicos</h6>
        <a href="{{ route('pessoa.juridica') }}" class="btn btn-primary pull-right"> 
			<span class="fa fa-plus"></span> 
			<span class="fa fa-user-circle-o"></span> P. Jurídica
		</a> 
        <a href="{{ route('pessoa.fisica') }}" class="btn btn-info pull-right"> 
			<span class="fa fa-plus"></span> 
			<span class="fa fa-user-circle"></span> P. Física
		</a> 
		<a href="{{ route('pessoa.tecnico') }}" class="btn btn-success pull-right"> 
			<span class="fa fa-plus"></span> 
			<span class="fa fa-user-o"></span> Técnico
		</a>
        
        <div class="table-responsive m-t-40">
			<table id="datatable" class="display nowrap table table-hover table-striped table-bordered table-responsive" cellspacing="0">
				<thead>
					<tr>
						<!-- <th> <input type="checkbox" name="select-all-customer"> </th> -->
						<th>Tipo</th>
						<th>CPF/CNPJ</th>
						<th>Nome</th>
						<th>Email</th>
						<th>Filiação</th>
						<th>Ações</th>
					</tr>
				</thead>
				<tbody>

					@foreach ($pessoas as $pessoa)
						<tr>
							<!-- <td> <input type="checkbox" name="select-customer"> </td> -->
							<td>{{ $pessoa->descricao_tipo }}</td>
							<td>{{ $pessoa->cpf_cnpj }}</td>
							<td>{{ $pessoa->nome }}</td>
							<td>{{ $pessoa->email }}</td>
							<td>
								@if( $pessoa->tipo == 3 && $pessoa->matricula()->filiado )
									SIM
								@else
									NÂO
								@endif
							</td>
							<td>
								<div class="btn-group">
                                    <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <span class="mdi mdi-account-settings"></span>
                                    </button>
                                    <div class="dropdown-menu" x-placement="top-start" style="position: absolute; transform: translate3d(0px, -2px, 0px); top: 0px; left: 0px; will-change: transform;">
                                        <a class="dropdown-item" href="{{ route('filiado.show', ['id' => $filiado->id]) }}">
                                        	<span class="mdi mdi-account-card-details"></span> Detalhar
                                        </a>
                                        <a class="dropdown-item" href="{{ route('filiado.edit', ['id' => $filiado->id]) }}">
                                        	<span class="mdi mdi-account-edit"></span> Alterar
                                        </a>
                                        <a class="dropdown-item" href="{{ route('filiado.activate', ['id' => $filiado->id]) }}">
                                        	<span class="mdi mdi-face-profile"></span> Tornar Técnico
                                        </a>
                                    </div>
                                </div>
							</td>
						</tr>
					@endforeach

				</tbody>

				<tfoot>
					<tr>
						<th>Tipo</th>
						<th>CPF/CNPJ</th>
						<th>Nome</th>
						<th>Email</th>
						<th>Filiação</th>
						<th>Ações</th>
					</tr>
				</tfoot>
			</table>  	
        </div>
	</div>
</div>

@endsection

@section('scripts')
	<script src="{{ asset('assets/plugins/sticky-kit-master/dist/sticky-kit.min.js') }}"></script>
	<!-- <script src="{{ asset('js/datatables.min.js') }}"></script> -->
	<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.min.js') }}"></script>
	<!-- start - This is for export functionality only -->
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
	<script type="text/javascript">
		var exportTitle = 'Filiados';
		
		$(document).ready(function() {
			
			$('#datatable tfoot th').each( function (index, value) {
		        var title = $(this).text();

		        if (index == 0) {
		        	
		        }else if (title != 'Ações'){
		        	$(this).html( '<input class="form-control" type="text" placeholder="Buscar por '+title+'" />' );
		        }

		    } );
			
			var counter = 0;

			var table = $('#datatable').DataTable({
				initComplete: function () {
		            this.api().columns().every( function () {
		                var that = this;
		                
		                if (counter == 0) {
		                	var select = $('<select class="form-control"><option value="">Por Tipo</option></select>')
			                    .appendTo( $(that.footer()).empty() )
			                    .on( 'change', function () {
			                        var val = $.fn.dataTable.util.escapeRegex(
			                            $(this).val()
			                        );
			 
			                        that
			                            .search( val ? '^'+val+'$' : '', true, false )
			                            .draw();
			                    } );
			 
			                that.data().unique().sort().each( function ( d, j ) {
			                    select.append( '<option value="'+d+'">'+d+'</option>' )
			                } );
		                }else{
		                	$( 'input', this.footer() ).on( 'keyup change', function () {
					            if ( that.search() !== this.value ) {
					                that
					                    .search( this.value )
					                    .draw();
					            }
					        } );
		                }

				        counter += 1;
		            } );
		        },
		    	dom: 'Bfrtip',
		        buttons: [
					{
						extend: 'csv',
						title: exportTitle
					}, 
					{
						extend: 'excel',
						title: exportTitle
					}, 
					{
						extend: 'pdf',
						title: exportTitle
					}, 
					{
						extend: 'print',
						title: exportTitle
					}
		        ],
		    	/*'columnDefs': [
	    			{"searchable": true, "targets": 2}
		    	],*/
		    	'language':{
		    		"search":"Buscar registros",
		    		"emptyTable": "Não registros",
		    		"zeroRecords": "Não foram encontrados registros",
		    		"lengthMenu": "Exbir _MENU_ registros",
		    		"infoFiltered": "(filtrados de _MAX_ registros)",
		    		"info": "Exibindo _START_ a _END_ de _TOTAL_ registros",
		    		"infoEmpty": "Exibindo 0 a 0 de 0 registros",
		    		"paginate": {
		    			"first": "Primeira página",
		    			"last": "Última página",
		    			"next": "Próximo",
		    			"previous": "Anterior"
		    		}
		    	}
			});
		} );
	</script>

@endsection

resources/views/pessoa/juridica.blade.php
@extends('layouts.dashboard')

@section('title', 'Adicionar Pessoa Jurídica')

@section('content')
	<form action="{{ route('pessoa.store') }}" method="POST">
		<div class="col-md-12">
			<div class="card">
				<div class="card-body">
					<div>
						<h3 class="card-title m-b-5"><span class="lstick"></span>Adicionar Pessoa Jurídica</h3>
					</div>
					{{ csrf_field() }}
					<div class="panel panel-default">
						<div class="panel-body">
							<input name="pessoa[tipo]" type="hidden" value="1" />

							<div class="row">
								<div class="form-group col-md-3">
									<label>CNPJ *</label>
									<input type="text" name="pessoa[cpf_cnpj]" class="form-control" required />
								</div>
								
								<div class="form-group col-md-3">
									<label>Inscrição Estadual</label>
									<input type="text" name="pessoa[inscricao_estadual]" class="form-control" />
								</div>
								
								<div class="form-group col-md-6">
									<label>Razão Social</label>
									<input type="text" name="pessoa[razao_social]" class="form-control" />
								</div>
							</div>
							
							@include('shared.pessoa')
						</div>
					</div>
				</div>

				<input type="submit" class="btn btn-success" value="Cadastrar">
			</div>
		</div>
	</form>			
@endsection

@section('scripts')
@endsection

resources/views/pessoa/tecnico.blade.php
@extends('layouts.dashboard')

@section('title', 'Adicionar Técnico')

@section('content')
	<form action="{{ route('pessoa.store') }}" method="POST">
		<div class="col-md-12">

			<div class="card">
				<div class="card-body">
					<div>
						<h3 class="card-title m-b-5"><span class="lstick"></span>Adicionar Técnico</h3>
					</div>
					{{ csrf_field() }}
					<div class="panel panel-default">
						<div class="panel-body">
							<input name="pessoa[tipo]" type="hidden" value="3" />

							<div class="row">
								<div class="form-group col-md-3">
									<label>CPF *</label>
									<input type="text" name="pessoa[cpf_cnpj]" class="form-control" required />
								</div>
								
								<div class="form-group col-md-3">
									<label>RG</label>
									<input type="text" name="pessoa[rg]" class="form-control" />
								</div>
								
								<div class="form-group col-md-3">
									<label>UF</label>
									<input type="text" name="pessoa[rg_uf]" class="form-control" />
								</div>

								<div class="form-group col-md-3">
									<label>Órgão Expedidor</label>
									<input type="text" name="pessoa[rg_orgao]" class="form-control" />
								</div>
							</div>
							
							@include('shared.pessoa')
						</div>
					</div>
				</div>
			</div>
			
			<div class="card">
				<div class="card-body">
					<div>
						<h3 class="card-title m-b-5"><span class="lstick"></span>Dados Funcionais</h3>
					</div>
					<div class="panel panel-default">
						<div class="panel-body">

							<div class="row">
								<div class="form-group col-md-2">
									<label>Matrícula *</label>
									<input type="text" name="matricula[id]" class="form-control" placeholder="000000-0" value="{{ old('matricula.id') }}">
								</div>
								<div class="form-group col-md-4">
									<label>Situação</label>
									<input type="text" name="matricula[situacao]" class="form-control" placeholder="" value="{{ old('matricula.situacao') }}">
								</div>
								<div class="form-group col-md-4">
									<label>Lotação</label>
									<input type="text" name="matricula[lotacao]" class="form-control" placeholder="" value="{{ old('matricula.lotacao') }}">
								</div>
							</div>

							<div class="row">
								<div class="form-group col-md-4">
									<label>Classe</label>
									<input type="text" name="matricula[classe]" class="form-control" placeholder="" value="{{ old('matricula.classe') }}">
								</div>
								<div class="form-group col-md-4">
									<label>Nível</label>
									<input type="text" name="matricula[nivel]" class="form-control" placeholder="" value="{{ old('matricula.nivel') }}">
								</div>
								<div class="form-group col-md-4">
									<label>Data de admissão</label>
									<input type="date" name="matricula[data_admissao]" class="form-control data" placeholder="" value="{{ old('matricula.data_admissao') }}">
								</div>
							</div>
							
						</div>
					</div>
				</div>
			</div>
			
			<div class="card">
				<div class="card-body">
					<div>
						<h3 class="card-title m-b-5"><span class="lstick"></span>Filiação</h3>
					</div>
					<div class="panel panel-default">
						<div class="panel-body">

							<div class="row">
								<div class="form-group col-md-3">
									<input type="checkbox" name="matricula[filiado]" class="form-control" value="{{ old('matricula.id') }}" />
									<label>Filiado</label>
								</div>
								<div class="form-group col-md-4">
									<label>Data de Filiação</label>
									<input type="date" name="matricula[data_filiacao]" class="form-control" placeholder="" value="{{ old('matricula.data_filiacao') }}" />
								</div>
								<div class="form-group col-md-4">
									<label>Data de Desfiliação</label>
									<input type="date" name="matricula[data_desfiliacao]" class="form-control" placeholder="" value="{{ old('matricula.data_desfiliacao') }}" />
								</div>
							</div>
							
						</div>
					</div>
				</div>
			</div>

			<input type="submit" class="btn btn-success" value="Cadastrar">
		</div>
	</form>
@endsection

@section('scripts')
@endsection